// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smr;

#nullable disable

namespace smr.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241217101735_conect")]
    partial class conect
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("smr.Entitis.Renter", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryNameOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("renters");
                });

            modelBuilder.Entity("smr.Entitis.Tourist", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryNameOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("tourists");
                });

            modelBuilder.Entity("smr.Entitis.Turn", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Renterid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TouristId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Renterid");

                    b.HasIndex("TouristId")
                        .IsUnique();

                    b.ToTable("turns");
                });

            modelBuilder.Entity("smr.Entitis.Turn", b =>
                {
                    b.HasOne("smr.Entitis.Renter", null)
                        .WithMany("turns")
                        .HasForeignKey("Renterid");

                    b.HasOne("smr.Entitis.Tourist", "tourist")
                        .WithOne("turn")
                        .HasForeignKey("smr.Entitis.Turn", "TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tourist");
                });

            modelBuilder.Entity("smr.Entitis.Renter", b =>
                {
                    b.Navigation("turns");
                });

            modelBuilder.Entity("smr.Entitis.Tourist", b =>
                {
                    b.Navigation("turn")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
